const express = require('express')
const userController = require("../controllers/userController")
const router = express.Router()

router.route('/login')
  .post(userController.login)
router.route('/register')
  .post(userController.register)
router.route('/user/:id')
  .delete(userController.delete)
  .patch(userController.updateUser)
